export const PRICING_PLANS = [
  {
    id: 'starter',
    name: 'Starter Backup',
    price: '₹299',
    period: '/ mo',
    description: 'Perfect for individual creators to secure their vital Google Workspace data.',
    features: [
      '100 GB Secure Backup Storage',
      'Gmail & Google Drive backup',
      'Weekly automated background syncs',
      'Standard 24-hour file recovery',
      'Basic Email Support',
    ],
    recommended: false,
    ctaText: 'Start Free Trial',
  },
  {
    id: 'pro',
    name: 'Professional Cloud',
    price: '₹799',
    period: '/ mo',
    description: 'Ideal for power users, freelancers, and small teams requiring robust security.',
    features: [
      '1 TB High-Speed Cloud Storage',
      'Complete Suite: Gmail, Drive, Photos, Contacts & Calendar',
      'Daily automatic incremental syncs',
      'AES 256-bit zero-knowledge encryption',
      '1-Click granular restoration tools',
      'Priority 24/7 chat support',
    ],
    recommended: true,
    ctaText: 'Connect Google Workspace',
  },
  {
    id: 'enterprise',
    name: 'Enterprise Sync',
    price: '₹1,999',
    period: '/ mo',
    description: 'Advanced data protection with elite controls and limitless scalability.',
    features: [
      'Unlimited Backup Storage',
      'All Workspace users and drives included',
      'Real-time & Hourly automated syncs',
      'Dedicated compliance audit logs',
      '99.9% Uptime SLA guaranteed',
      'Personal Accounts & Solutions Manager',
    ],
    recommended: false,
    ctaText: 'Contact Enterprise',
  },
];
